/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#490013",
        "on-secondary-fixed": "#403f3f",
        "inverse-surface": "#f9f9f9",
        "on-primary": "#2724b8",
        "tertiary-fixed": "#ced6f5",
        "surface-container-high": "#1f1f1f",
        "on-surface": "#e5e5e5",
        "primary-dim": "#b0b2ff",
        "tertiary-container": "#ced6f5",
        "secondary-fixed-dim": "#d6d4d3",
        "error-dim": "#b95463",
        "outline": "#757575",
        "on-tertiary-fixed": "#2f384f",
        "outline-variant": "#484848",
        "on-secondary-container": "#c1bfbe",
        "tertiary-fixed-dim": "#c0c9e6",
        "on-background": "#e5e5e5",
        "on-tertiary-container": "#424a63",
        "surface-container": "#191919",
        "error-container": "#7f2737",
        "inverse-primary": "#494bd7",
        "primary-fixed-dim": "#d1d0ff",
        "surface-bright": "#2c2c2c",
        "primary-fixed": "#e1e0ff",
        "tertiary": "#dee5ff",
        "error": "#ec7c8a",
        "on-tertiary": "#4a536c",
        "inverse-on-surface": "#555555",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#3c3b3b",
        "surface-container-highest": "#262626",
        "on-tertiary-fixed-variant": "#4b546d",
        "on-primary-fixed-variant": "#4647d3",
        "on-primary-fixed": "#2622b7",
        "on-primary-container": "#ccccff",
        "secondary-dim": "#9f9d9d",
        "surface-dim": "#0e0e0e",
        "surface-container-low": "#131313",
        "surface": "#0e0e0e",
        "on-error-container": "#ff97a3",
        "surface-container-lowest": "#000000",
        "surface-variant": "#262626",
        "on-surface-variant": "#ababab",
        "on-secondary": "#202020",
        "primary-container": "#2f2ebe",
        "background": "#0e0e0e",
        "tertiary-dim": "#c0c9e6",
        "primary": "#c0c1ff",
        "on-secondary-fixed-variant": "#5c5b5b",
        "secondary": "#9f9d9d",
        "surface-tint": "#c0c1ff",
        "success": "#7de3a4",
        "warning": "#f3c969",
      },
      boxShadow: {
        "flux": "0 24px 80px rgba(0, 0, 0, 0.42), 0 0 40px rgba(192, 193, 255, 0.08)",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
